[features]
seeds = false

[registry]
url = "https://anchor.projectserum.com"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
omnisol = "6sccaGNYx7RSjVgFD13UKE7dyUiNavr2KXgeqaQvZUz7"

[programs.devnet]
omnisol = "6sccaGNYx7RSjVgFD13UKE7dyUiNavr2KXgeqaQvZUz7"

[programs.testnet]
omnisol = "6sccaGNYx7RSjVgFD13UKE7dyUiNavr2KXgeqaQvZUz7"

[[test.genesis]]
address = "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy"
program = "target/deploy/stake_pool.so"

[[test.genesis]]
address = "unpXTU2Ndrc7WWNyEhQWe4udTzSibLPi25SXv2xbCHQ"
program = "target/deploy/unstake_it.so"
